
# ??? ??? ?? ????
# ? ???????? ?? ???? ???? ?
# ??? ?????
oauth:
  kakao:
    client_id:  # REST API ?
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret:  # Client Secret ?
    scope: profile_nickname, profile_image